### ISSUE TITLE
Handle 429 status

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.osm#1]
Currently, the service we use (https://nominatim.openstreetmap.org) returns [HTTP status code 429](http://httpstatusdogs.com/429-too-many-requests) if queried to often, but this isn't properly handled in the current version - the look-up keeps on going. Also, after a while the server seems to block the requests entirely, causing the following error:

```
May 17 22:58:23  [info] $backTrace = #0 /var/www/sites/all/modules/civicrm/CRM/Core/Error.php(777): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 [internal function](): CRM_Core_Error::exceptionHandler(Object(PEAR_Error))
#2 /var/www/sites/all/modules/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(PEAR_Error))
#3 /var/www/sites/all/modules/civicrm/packages/PEAR.php(566): PEAR_Error->PEAR_Error("", 0, 16, (Array:2), NULL)
#4 /var/www/sites/all/modules/civicrm/packages/Net/Socket.php(156): PEAR->raiseError("", 0)
#5 /var/www/sites/all/modules/civicrm/packages/HTTP/Request.php(737): Net_Socket->connect("ssl://nominatim.openstreetmap.org", 443, NULL, NULL, NULL)
#6 /var/www/sites/default/civicrm-extensions/de.systopia.osm/CRM/Utils/Geocode/OpenStreetMapCoding.php(139): HTTP_Request->sendRequest()
#7 /var/www/sites/all/modules/civicrm/CRM/Utils/Address/BatchUpdate.php(183): CRM_Utils_Geocode_OpenStreetMapCoding::format((Array:5), TRUE)
#8 /var/www/sites/all/modules/civicrm/CRM/Utils/Address/BatchUpdate.php(108): CRM_Utils_Address_BatchUpdate->processContacts(Object(CRM_Core_Config), TRUE, FALSE)
#9 /var/www/sites/all/modules/civicrm/api/v3/Job.php(155): CRM_Utils_Address_BatchUpdate->run()
[...]
```

What needs to be done:
1. Properly detect and process 429 calls - what exactly should happen here needs to be discussed, but at least we should abort the batch update process if there is one.
2. Remove/Reduce `Geocoding failed. Address data is incomplete.` and `Geocoding failed, invalid response code 429` spamming of error log.
3. Update readme file accordingly.

**Comment by thomst** [comment]
The commits https://github.com/systopia/de.systopia.osm/commit/037798e9ccaa48b559869b379992ef84c21ccd0e and https://github.com/systopia/de.systopia.osm/commit/e14c82805475232401bc3f0605d0ba344a770fec should solve this issue.
