### ISSUE TITLE
Not available for CiviCRM 4.7

### ISSUE THREAD

**Issue by JohnFF** [systopia/de.systopia.osm#11]
Hi,

Please can you update this and release it for CiviCRM 4.7?

Thanks,

John

**Comment by bjendres** [comment]
@JohnFF: Good point. Do you have any funding for this? Alternatively you could just give it a try and report the issues.

**Comment by JohnFF** [comment]
No funding sadly. There's usage of a deprecated function. As you know the
code, and 4.6->4.7 isn't a dramatic upgrade extensions-wise, it'd probably
only take a few minutes to fix up tbh.

John

**Comment by bjendres** [comment]
Sounds good. Please create a PR and I'll release it for 4.7!

**Comment by JohnFF** [comment]
I don't know the code like you do ;)

**Comment by bjendres** [comment]
@JohnFF: Andy Clark says it works fine for him. Have you tried the current version on 4.7?

**Comment by JohnFF** [comment]
Yes. 4.7.19

**Comment by JohnFF** [comment]
This will be fixed when you create a new 4.7 release :)

**Comment by twomice** [comment]
FYI, recent changes to Google's geocoding service (reference: https://mapsplatform.googleblog.com/2018/05/introducing-google-maps-platform.html) I'm switching to this extension in CiviCRM 4.7/5.x, and it works fine for me. Looks like info.xml is already reflecting that. I recommend adding a tag for a new release so that it shows up as such on https://civicrm.org/extensions/openstreetmap-geocoding and on the in-app Extensions page for easy installs.

**Comment by bjendres** [comment]
Thanks @twomice, I created a new release highlighting the 4.7/5.0 compatibility.

With respect to adding that tag for in-app installation: we've been trying to achieve this with a number of our extensions, but they always said that it needs to be reviewed which then never happened. How would you think we should go about doing this?

**Comment by twomice** [comment]
Ah, I see. I was thinking the extension was already reviewed and set up for in-app installation. If it's not, then yes that review still needs to happen. There's a backup of pending reviews, based on the volume of review requests and the number of volunteer reviewers. If you've created the Review Request ticket, that's all you can do, and wait for the review. Of course, you could also put a "bump" comment on that ticket to possibly leverage the "squeaky wheel" principle.
