### ISSUE TITLE
Incompatible with CiviCRM 5.27+ (was: "Error geocoding")

### ISSUE THREAD

**Issue by edvanleeuwen** [systopia/de.systopia.osm#14]
I am getting the following error when saving an address in CiviCRM:

`Warning: require_once(HTTP/Request.php): failed to open stream: No such file or directory in require_once() (regel 140 van /home/xxx/domains/xxx.nl/public_html/sites/default/files/civicrm/ext/de.systopia.osm/CRM/Utils/Geocode/OpenStreetMapCoding.php).`

What am I missing?

Drupal 7.72
CiviCRM 5.27.1
OSM 1.2.1

**Comment by reswild** [comment]
The HTTP_Request package has been removed from the latest version of CiviCRM (see https://github.com/civicrm/civicrm-packages/pull/293). I guess this code will need to be rewritten to use the GuzzleHttp\Client instead.

**Comment by reswild** [comment]
Here is a suggested patch to switch to using GuzzleHttp: https://github.com/reswild/de.systopia.osm/commit/90e926415080d0d3487ae046fe4eb3d0bec8460b

**Comment by bjendres** [comment]
> Here is a suggested patch to switch to using GuzzleHttp: [reswild@90e9264](https://github.com/reswild/de.systopia.osm/commit/90e926415080d0d3487ae046fe4eb3d0bec8460b)

Thanks for that @reswild, great stuff. However, we would have to add a version switch, so we don't break the extension for installations with CiviCRM < ``5.27`` (or whenever ``GuzzleHttp`` was added). Would you be able/willing to create a PR?

**Comment by reswild** [comment]
Sure, I can create a PR for this.

I think GuzzleHttp has been available since version 5.0.

**Comment by bjendres** [comment]
Thanks for the PR, @reswild 

@all: I created release [1.3-alpha1](https://github.com/systopia/de.systopia.osm/releases/tag/1.3-alpha1), could you check if it works properly? If so, I'll create a full release.

**Comment by andrew-cormick-dockery** [comment]
I can confirm that the previous version caused an error with Civi v5.28 when I tried to create a contact with an address, but this version worked fine and encoded the test address correctly.

**Comment by bmango** [comment]
I was getting the same error with Civi 5.28.3: 

`Warning: require_once(HTTP/Request.php): failed to open stream: No such file or directory in require_once()`

Upgrading to 1.3-alpha1 solved the problem for me. Thank you very much :)

**Comment by bjendres** [comment]
Thanks! I will realease a ``1.3`` soon

**Comment by bjendres** [comment]
released with ``1.3``, thanks @reswild
