### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by bmango** [systopia/de.systopia.osm#21]
Using php 7.4 I'm getting the error message above. This seems to be coming from line 133 in osm.civix.php. I have swapped

if ($entry{0} == '.') {

with

if ($entry[0] == '.') {

Which I think has fixed it

**Comment by colemanw** [comment]
This can be closed thanks to #19

**Comment by bjendres** [comment]
> This can be closed thanks to #19

Thanks
