### ISSUE TITLE
Support Question: High level usage - Can I populate a 'voting district' field for each user based on their address?

### ISSUE THREAD

**Issue by HeneryH** [systopia/de.systopia.osm#32]
Assuming I go into the OpenStreetMaps open source mapper and define voting districts for my local town?

How would this workstream look in CiviCRM?

**Comment by bjendres** [comment]
> How would this workstream look in CiviCRM?

Hi @HeneryH. I'm not sure where you're going with this, but this extension's purpose is (so far) to do geocoding, i.e. resolve addresses in the the CiviCRM database to geo-coordinates.

**Comment by HeneryH** [comment]
I'm trying to define a voting district by some mechanism and then have each
contact be auto-defined to be in that district based on their address.  Not
have to look up each contact manually and then set their district.

**Comment by bjendres** [comment]
Ah, understood. Well, I guess the only thing this extension can do for you then, is get the geo-coordinates for all your contacts (with a valid address), but the matching of these coordinates to one of your voting districts is beyond its scope. 

There might be another CiviCRM extension to do this already, maybe post a question on https://civicrm.stackexchange.com/

**Comment by HeneryH** [comment]
Ah, I thought the Areas extension could let me define areas (ie districts)
but then I wasn't sure what could be done with them.

**Comment by HeneryH** [comment]
Wrong thread.  But similar.

**Comment by bjendres** [comment]
> Ah, I thought the Areas extension could let me define areas (ie districts)

I think it does, but simply as a simple entity, not via geo-coordinates.
